name: Kasper-Actions

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  Build-APK:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Module app
        run: |
          chmod +x ./gradlew
          ./gradlew build
          
      - name: Build Module kasper-chat-lite
        run: ./gradlew :kasper-chat-lite:assembleDebug 
        
      - name: Archive APK files
        run: |
          mkdir -p apk
          cp moduleA/build/outputs/apk/debug/app-debug.apk apk/
          cp moduleB/build/outputs/apk/debug/kasper-chat-lite-debug.apk apk/
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: apk/


